# ODQ environments
# PostgreSQL
development:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq
  username: odq_app
  password: odq_app
  schema_search_path: "odq_info"
  pool: 5

# TEST environment
# PostgreSQL
test:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_test
  username: odq_app
  password: odq_app
  schema_search_path: "odq_info"
  pool: 5

# PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  database: ODQ_STEP1
  pool: 5

#  adapter: sqlite3
#  database: db/ODQ_DEV.sqlite3
#  pool: 5
#  timeout: 5000
