# ODQ environments
# PostgreSQL
development:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_app_dev
  username: odq_app
  password: odq_app
  schema_search_path: "odq_app"
  pool: 5

# TEST environment
# PostgreSQL
test:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_app_test
  username: odq_app
  password: odq_app
  schema_search_path: "odq_app"
  pool: 5

# EVALUATION environment
# PostgreSQL
eval:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_app_eval
  username: odq_app
  password: odq_app
  schema_search_path: "odq_app,odq_dwh"
  pool: 5

# INTEGRATION environment
# PostgreSQL
int:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_app_eval
  username: odq_app
  password: odq_app
  schema_search_path: "odq_app"
  pool: 5

# INTEGRATION environment
# PostgreSQL
poc:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_app_poc
  username: odq_app
  password: odq_app
  schema_search_path: "odq_app"
  pool: 5

# PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  database: ODQ_STEP1
#  schema_search_path: "odq_info"
  pool: 5

#MSSQL environment
MSSQL:
  adapter: sqlserver
  username: 'odq_app'
  password: 'odq_app'
  dataserver: 'W2008SERVER'
  database: 'ODQ'
  appname: 'ODQ'

#ORACLE environment
ORACLE:
  adapter: oracle_enhanced
  database: INFO
  username: ODQ_DEV
  password: ODQ_DEV

