# ODQ environments
# PostgreSQL
development:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_app
  username: odq_app
  password: odq_app
#  schema_search_path: "odq_info"
  pool: 5

# TEST environment
# PostgreSQL
test:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: odq_test
  username: odq_app
  password: odq_app
#  schema_search_path: "odq_info"
  pool: 5

# PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  database: ODQ_STEP1
#  schema_search_path: "odq_info"
  pool: 5

#MSSQL environment
MSSQL:
  adapter: sqlserver
  username: 'odq_app'
  password: 'odq_app'
  dataserver: 'W2008SERVER'
  database: 'ODQ'
  appname: 'ODQ'

#ORACLE environment
ORACLE:
  adapter: oracle_enhanced
  database: INFO
  username: ODQ_APP
  password: ODQ_APP

