class RemoveRedundantIds < ActiveRecord::Migration[5.0]
  def change
    remove_column :breaches, :odq_object_id, :integer
    remove_column :breaches, :odq_unique_id, :integer
    remove_column :business_areas, :odq_object_id, :integer
    remove_column :business_areas, :odq_unique_id, :integer
    remove_column :business_flows, :odq_object_id, :integer
    remove_column :business_flows, :odq_unique_id, :integer
    remove_column :business_processes, :odq_object_id, :integer
    remove_column :business_processes, :odq_unique_id, :integer
    remove_column :business_objects, :odq_object_id, :integer
    remove_column :business_objects, :odq_unique_id, :integer
    remove_column :business_rules, :odq_object_id, :integer
    remove_column :business_rules, :odq_unique_id, :integer
    remove_column :data_processes, :odq_object_id, :integer
    remove_column :data_processes, :odq_unique_id, :integer
    remove_column :landscapes, :odq_object_id, :integer
    remove_column :landscapes, :odq_unique_id, :integer
    remove_column :playgrounds, :odq_object_id, :integer
    remove_column :playgrounds, :odq_unique_id, :integer
    remove_column :scopes, :odq_object_id, :integer
    remove_column :scopes, :odq_unique_id, :integer
    remove_column :mappings, :odq_object_id, :integer
    remove_column :mappings, :odq_unique_id, :integer
    remove_column :mappings_lists, :odq_object_id, :integer
    remove_column :mappings_lists, :odq_unique_id, :integer
    remove_column :notifications, :odq_object_id, :integer
    remove_column :notifications, :odq_unique_id, :integer
    remove_column :organisations, :odq_object_id, :integer
    remove_column :organisations, :odq_unique_id, :integer
    remove_column :parameters, :odq_object_id, :integer
    remove_column :parameters, :odq_unique_id, :integer
    remove_column :parameters_lists, :odq_object_id, :integer
    remove_column :parameters_lists, :odq_unique_id, :integer
    remove_column :territories, :odq_object_id, :integer
    remove_column :territories, :odq_unique_id, :integer
    remove_column :values, :odq_object_id, :integer
    remove_column :values_lists, :odq_unique_id, :integer
  end
end
