require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListsOfParametersController do

  # This should return the minimal set of attributes required to create a valid
  # ListsOfParameter. As you add validations to ListsOfParameter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ListsOfParametersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lists_of_parameters as @lists_of_parameters" do
      lists_of_parameter = ListsOfParameter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lists_of_parameters).should eq([lists_of_parameter])
    end
  end

  describe "GET show" do
    it "assigns the requested lists_of_parameter as @lists_of_parameter" do
      lists_of_parameter = ListsOfParameter.create! valid_attributes
      get :show, {:id => lists_of_parameter.to_param}, valid_session
      assigns(:lists_of_parameter).should eq(lists_of_parameter)
    end
  end

  describe "GET new" do
    it "assigns a new lists_of_parameter as @lists_of_parameter" do
      get :new, {}, valid_session
      assigns(:lists_of_parameter).should be_a_new(ListsOfParameter)
    end
  end

  describe "GET edit" do
    it "assigns the requested lists_of_parameter as @lists_of_parameter" do
      lists_of_parameter = ListsOfParameter.create! valid_attributes
      get :edit, {:id => lists_of_parameter.to_param}, valid_session
      assigns(:lists_of_parameter).should eq(lists_of_parameter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListsOfParameter" do
        expect {
          post :create, {:lists_of_parameter => valid_attributes}, valid_session
        }.to change(ListsOfParameter, :count).by(1)
      end

      it "assigns a newly created lists_of_parameter as @lists_of_parameter" do
        post :create, {:lists_of_parameter => valid_attributes}, valid_session
        assigns(:lists_of_parameter).should be_a(ListsOfParameter)
        assigns(:lists_of_parameter).should be_persisted
      end

      it "redirects to the created lists_of_parameter" do
        post :create, {:lists_of_parameter => valid_attributes}, valid_session
        response.should redirect_to(ListsOfParameter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lists_of_parameter as @lists_of_parameter" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListsOfParameter.any_instance.stub(:save).and_return(false)
        post :create, {:lists_of_parameter => {  }}, valid_session
        assigns(:lists_of_parameter).should be_a_new(ListsOfParameter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListsOfParameter.any_instance.stub(:save).and_return(false)
        post :create, {:lists_of_parameter => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lists_of_parameter" do
        lists_of_parameter = ListsOfParameter.create! valid_attributes
        # Assuming there are no other lists_of_parameters in the database, this
        # specifies that the ListsOfParameter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListsOfParameter.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => lists_of_parameter.to_param, :lists_of_parameter => { "these" => "params" }}, valid_session
      end

      it "assigns the requested lists_of_parameter as @lists_of_parameter" do
        lists_of_parameter = ListsOfParameter.create! valid_attributes
        put :update, {:id => lists_of_parameter.to_param, :lists_of_parameter => valid_attributes}, valid_session
        assigns(:lists_of_parameter).should eq(lists_of_parameter)
      end

      it "redirects to the lists_of_parameter" do
        lists_of_parameter = ListsOfParameter.create! valid_attributes
        put :update, {:id => lists_of_parameter.to_param, :lists_of_parameter => valid_attributes}, valid_session
        response.should redirect_to(lists_of_parameter)
      end
    end

    describe "with invalid params" do
      it "assigns the lists_of_parameter as @lists_of_parameter" do
        lists_of_parameter = ListsOfParameter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListsOfParameter.any_instance.stub(:save).and_return(false)
        put :update, {:id => lists_of_parameter.to_param, :lists_of_parameter => {  }}, valid_session
        assigns(:lists_of_parameter).should eq(lists_of_parameter)
      end

      it "re-renders the 'edit' template" do
        lists_of_parameter = ListsOfParameter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListsOfParameter.any_instance.stub(:save).and_return(false)
        put :update, {:id => lists_of_parameter.to_param, :lists_of_parameter => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lists_of_parameter" do
      lists_of_parameter = ListsOfParameter.create! valid_attributes
      expect {
        delete :destroy, {:id => lists_of_parameter.to_param}, valid_session
      }.to change(ListsOfParameter, :count).by(-1)
    end

    it "redirects to the lists_of_parameters list" do
      lists_of_parameter = ListsOfParameter.create! valid_attributes
      delete :destroy, {:id => lists_of_parameter.to_param}, valid_session
      response.should redirect_to(lists_of_parameters_url)
    end
  end

end
